# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog de LoïcG
email: gerbaudloic@gmail.com
description: > #
  Blog personnel de Loïc Gerbaud, père/développeur/bricoleur.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.loicg.net" # the base hostname & protocol for your site
github_username:  chibani
locale: french
branch: master
repository_url: https://github.com/chibani/chibani.github.io

# Build settings
markdown: kramdown

# GH settings
lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false

github: [metadata]
kramdown:
  input: GFM
hard_wrap: false
gems:
  - jekyll-paginate
  - jekyll-redirect-from
analytics:
    google:
        tracking_id: UA-2703255-5
